In [1]:
import numpy as np
import pandas as pd

In [9]:
def pol(z):
    return np.array([np.abs(z),(180/np.pi)*np.angle(z)])

def rec(z):
    return np.array([np.real(z),np.imag(z)])

def l_t(v,f,l_,r,l,c,g,p_c,fp,tipo=1):
    
    if tipo == 1:
        ang = np.arccos(fp)
    else: 
        ang = -np.arccos(fp)
        
    w = 2*np.pi*f

    z = r + 1j*w*l
    Z = z*l_
    y = g + 1j*w*c
    Y = y*l_

    prop = np.sqrt(z*y)
    aten = np.real(prop)
    fase = np.imag(prop)

    len_wave = (2*np.pi)/fase
    vel_wave = len_wave*f

    v_r = V/np.sqrt(3)
    i_r = (p_c/(V*fp*np.sqrt(3)))*np.exp(-1j*np.arccos(fp))

    v_s = 0.5*((v_r + i_r*Z_c)*np.exp(l_*prop) + (v_r - i_r*Z_c)*np.exp(-l_*prop))
    i_s = 0.5*((v_r/Z_c + i_r)*np.exp(l_*prop) - (v_r/Z_c - i_r)*np.exp(-l_*prop))
    
    fasores = pd.DataFrame(np.round(np.array([pol(Z),pol(Y),pol(Z_c),
                                         pol(1e3*prop),pol(v_r),
                                         pol(i_r),pol(v_s),pol(i_s)]),5),
                       columns = ['modulo','angulo'],
                       index = ['Z LT','Y LT','IMP.CARAC.','Propagação',
                               'V_R','I_R','V_S','I_S'])

    cartes = pd.DataFrame(np.round(np.array([rec(Z),rec(Y),rec(Z_c),
                                             rec(1e3*prop),rec(v_r),
                                             rec(i_r),rec(v_s),rec(i_s)]),5),
                          columns = ['real','imaginario'],
                          index = ['Z LT','Y LT','IMP.CARAC.','Propagação',
                                   'V_R','I_R','V_S','I_S'])

    wave = pd.DataFrame(np.round(np.array([len_wave,vel_wave]),5),
                        columns = ['Valor'],
                        index = ['Comprimento de onda',
                                'Velocidade de onda'])
    
    return display(fasores,cartes,wave)

In [3]:
V = 500e3
f = 60
l_ = 294.84
r = 0.025 
l = 0.854e-3
c = 13.65e-9
g = 0.0375e-6
p_c = 550e6
fp = 0.85

In [4]:
w = 2*np.pi*f

z = r + 1j*w*l
Z = z*l_
y = 0 + 1j*w*c
Y = y*l_
Z_c = np.sqrt(Z/Y)

prop = np.sqrt(z*y)
aten = np.real(prop)
fase = np.imag(prop)

len_wave = (2*np.pi)/fase
vel_wave = len_wave*f

v_r = V/np.sqrt(3)
i_r = (p_c/(V*fp*np.sqrt(3)))*np.exp(-1j*np.arccos(fp))

v_s = 0.5*((v_r + i_r*Z_c)*np.exp(l_*prop) + (v_r - i_r*Z_c)*np.exp(-l_*prop))
i_s = 0.5*((v_r/Z_c + i_r)*np.exp(l_*prop) - (v_r/Z_c - i_r)*np.exp(-l_*prop))

In [11]:
l_t(V,f,l_,r,l,c,g,p_c,fp)

xl=0.321950415139882,bc=5.145928766580081e-06,z=(7.3709999999999996+94.9238603998428j),y=(1.1056499999999998e-05+0.0015172256375384709j),zc=(250.34671831554053-8.79190963477514j)

                  modulo    angulo
Z LT            95.20962  85.55979
Y LT             0.00152  89.58248
IMP.CARAC.     250.50105  -2.01134
Propagação       1.28909  87.57114
V_R         288675.13459   0.00000
I_R            747.15917 -31.78833
V_S         314433.89817  10.59710
I_S            598.13067   6.31120

                    real   imaginario
Z LT             7.37100     94.92386
Y LT             0.00001      0.00152
IMP.CARAC.     250.34672     -8.79191
Propagação       0.05463      1.28794
V_R         288675.13459      0.00000
I_R            635.08530   -393.59052
V_S         309071.12314  57824.88355
I_S            594.50569     65.75165

                            Valor
Comprimento de onda    4878.48929
Velocidade de onda   292709.35712

In [10]:
l_t(230e3,60,300,0.031,0.8435e-3,13.61e-9,0.0125e-6,230e6,0.85)

xl=0.3179920083963588,bc=5.13084912184285e-06,z=(9.3+95.39760251890765j),y=(3.7499999999999997e-06+0.001539254736552855j),zc=(249.25985227925239-11.816704681122141j)

                  modulo    angulo
Z LT            95.84984  84.43202
Y LT             0.00154  89.86041
IMP.CARAC.     249.53979  -2.71420
Propagação       1.28035  87.14622
V_R         288675.13459   0.00000
I_R            312.44838 -31.78833
V_S         286536.15739   5.07302
I_S            375.79774  48.80987

                    real   imaginario
Z LT             9.30000     95.39760
Y LT             0.00000      0.00154
IMP.CARAC.     249.25985    -11.81670
Propagação       0.06375      1.27877
V_R         288675.13459      0.00000
I_R            265.58112   -164.59240
V_S         285413.74151  25337.04099
I_S            247.48527    282.79848

                            Valor
Comprimento de onda    4913.47163
Velocidade de onda   294808.29795